### ISSUE TITLE
HassOS config

### ISSUE THREAD

**Issue by h3mmy** [Djelibeybi/hassio-addons#2]
I'm unable to find clear documentation around configuring this on HassOS. I want to set hardcoded discovery options. What would be the recommended way to go about this?

**Comment by Djelibeybi** [comment]
You mean for Photons Interactor? The first time it starts, it'll create a `/config/photons/interactor.yml` file. Just edit that and add whatever hardcoded discovery options you need.

**Comment by h3mmy** [comment]
It hasn't created that folder. The logs seem to indicate that goes just fine. I tried creating a /photons/lifx.yml to see if it got picked up, but it didn't.

**Comment by Djelibeybi** [comment]
It's not designed to pick up a file named `lifx.yml`. It will only look in your `/config` location for a folder named `photons` and a file named `interactor.yml`.

**Comment by Djelibeybi** [comment]
You can see from the `run` script that it should create `/config/photons/interactor.yml` if it doesn't already exist and only supports using a file of that name: https://github.com/Djelibeybi/hassio-addons/blob/main/photons-interactor/rootfs/etc/services.d/interactor/run

**Comment by h3mmy** [comment]
I have tried replacing /config/photons/interactor.yml unsuccessfully. 
I have tried the following with and without the interactor block. Each time I have also tried rebooting the host altogether.
I did see from the run script that it should create that file and yet it doesn't do so in the rootfs from what I can tell. I know HassOS is weird about not allowing any access to the root filesystem directly, but it certainly doesn't pop up wherever /config is mounted from.
`interactor:
  host: {{ .ip_address }}
  port: {{ .port }}

  database:
    uri: "{config_root}/interactor.db"

  daemon_options:
      limit: 30 # Limit of 30 messages inflight at any one time
      search_interval: 1800 # do a discovery every 30 minutes
      time_between_queries:
        LIGHT_STATE: 600 # label, power, hsbk every 10 minutes
        VERSION: null # The type of product can be cached forever
        FIRMWARE: 86400 # Cache the firmware version for a day
        GROUP: 780 # Cache group information for 13 minutes
        LOCATION: 9600 # Cache location information for 16 minutes

  zeroconf:
    enabled: true
    ip_address: {{ .ip_address }}
    name: {{ .hostname }}

discovery_options:
  hardcoded_discovery:
    d0xxxxxxxx5a: "10.0.0.12"`

**Comment by h3mmy** [comment]
For good measure, I tested with lifx-photons-core directly and used 
`export HARDCODED_DISCOVERY='{"d0xxxxxxxx5a": "10.0.0.12"}'`
`lifx lan:attr _ GetPower`

and that worked successfully. I just can't seem to get the hardcoded discovery setup in the home-assistant add-on.

**Comment by Djelibeybi** [comment]
Can you please paste the logs from the addon startup? Also, however you edit `configuration.yaml` for HA, check the same location for a `photons/interactor.yml` file.  You don't need to touch the container image itself. It mounts `/config` from the same location as `configuration.yaml`.

**Comment by Djelibeybi** [comment]
Also, could you please try running `curl` to see if Photons Interactor can find your devices via discovery:

```shell
curl -XPUT http://homeassistant.local:6100/v1/lifx/command -HContent-Type:application/json -d '{"command": "discover"}'
```

**Comment by h3mmy** [comment]
Logs from 'Add-on' menu:
```
2022-04-02 11:57:43,226 INFO    delfick_project.option_merge.collector Adding configuration from /root/.photons_apprc.yml
2022-04-02 11:57:43,245 INFO    delfick_project.addons Found lifx.photons.interactor addon
2022-04-02 11:57:45,117 INFO    delfick_project.addons Found lifx.photons.canvas addon
2022-04-02 11:57:45,120 INFO    delfick_project.addons Found lifx.photons.control addon
2022-04-02 11:57:45,193 INFO    delfick_project.addons Found lifx.photons.core addon
2022-04-02 11:57:45,195 INFO    delfick_project.addons Found lifx.photons.pytest addon
2022-04-02 11:57:45,199 INFO    delfick_project.addons Found lifx.photons.transport addon
2022-04-02 11:57:45,204 INFO    delfick_project.option_merge.collector Converting photons_app
2022-04-02 11:57:45,211 INFO    delfick_project.option_merge.collector Converting target_register
2022-04-02 11:57:45,213 INFO    delfick_project.option_merge.collector Converting reference_resolver_register
2022-04-02 11:57:45,214 INFO    delfick_project.option_merge.collector Converting targets
2022-04-02 11:57:45,220 INFO    delfick_project.option_merge.collector Converting discovery_options
2022-04-02 11:57:45,224 INFO    delfick_project.option_merge.collector Converting protocol_register
2022-04-02 11:57:45,264 INFO    delfick_project.option_merge.collector Converting interactor
2022-04-02 11:57:45,703 INFO    alembic.runtime.migration Context impl SQLiteImpl.
2022-04-02 11:57:45,704 INFO    alembic.runtime.migration Will assume non-transactional DDL.
2022-04-02 11:57:45,762 INFO    whirlwind.server Hosting server at http://0.0.0.0:6100
2022-04-02 11:57:45,776 INFO    photons_transport.transports.udp Creating datagram endpoint address=('255.255.255.255', 56700)  serial=None
```

Running the curl command returns `{}`. My goal is to hardcode the discovery to specific devices. Can I add config changes via REST Call? I didn't note that in the library anywhere but I wasn't super thorough.

**Comment by Djelibeybi** [comment]
So that's not the log output from my addon. That looks like you're either running the [upstream addon from Delfick](https://photons.delfick.com/apps/interactor/homeassistant.html) or something else. 

This is what the log output from my addon looks like:

```log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Photons Interactor
 Photons Interactor provides a local RESTful API for LIFX devices
-----------------------------------------------------------
 Add-on version: 0.12.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.6  (aarch64 / odroid-n2)
 Home Assistant Core: 2022.3.8
 Home Assistant Supervisor: 2022.03.dev0901
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] interactor.sh: executing... 
[cont-init.d] interactor.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[07:24:24] INFO: Starting Photons Interactor on homeassistant (192.168.254.10/16:6100)
```

The only way to make config changes is via the YAML file.

**Comment by Djelibeybi** [comment]
I've just updated my addon to v0.12.0.3 which enables the ability to re-enable Interactor's logging and to override the config file at runtime with the latest settings.

**Comment by h3mmy** [comment]
I noticed the version I have been using is 12.1.0 so I grew concerned. Turns out I've been using https://github.com/Djelibeybi/addon-photons-interactor/ this whole time. My apologies for the mistake. 

I have removed that and added the correct repo (hassio-addons). It crashes into a "bootloop" with the following error
```
[06:44:21] INFO: Starting Photons Interactor using /config/photons/interactor.yml
[06:44:21] INFO: Photons Interactor verbose logging enabled.
2022-04-04 06:44:22,356 INFO    delfick_project.option_merge.collector Adding configuration from /root/.photons_apprc.yml
2022-04-04 06:44:22,356 INFO    delfick_project.option_merge.collector Adding configuration from /config/photons/interactor.yml
2022-04-04 06:44:22,378 INFO    delfick_project.addons Found lifx.photons.canvas addon
2022-04-04 06:44:22,499 INFO    delfick_project.addons Found lifx.photons.control addon
2022-04-04 06:44:22,545 INFO    delfick_project.addons Found lifx.photons.core addon
2022-04-04 06:44:22,547 INFO    delfick_project.addons Found lifx.photons.pytest addon
2022-04-04 06:44:22,549 INFO    delfick_project.addons Found lifx.photons.transport addon
2022-04-04 06:44:22,550 INFO    delfick_project.addons Found lifx.photons.interactor addon
2022-04-04 06:44:23,140 INFO    delfick_project.option_merge.collector Converting photons_app
2022-04-04 06:44:23,150 INFO    delfick_project.option_merge.collector Converting target_register
2022-04-04 06:44:23,151 INFO    delfick_project.option_merge.collector Converting reference_resolver_register
2022-04-04 06:44:23,152 INFO    delfick_project.option_merge.collector Converting targets
2022-04-04 06:44:23,155 INFO    delfick_project.option_merge.collector Converting discovery_options
2022-04-04 06:44:23,158 INFO    delfick_project.option_merge.collector Converting protocol_register
2022-04-04 06:44:23,178 INFO    delfick_project.option_merge.collector Converting interactor
2022-04-04 06:44:23,406 INFO    alembic.runtime.migration Context impl SQLiteImpl.
2022-04-04 06:44:23,406 INFO    alembic.runtime.migration Will assume non-transactional DDL.
2022-04-04 06:44:23,435 INFO    whirlwind.server Hosting server at http://<no value>:6100
Traceback (most recent call last):
  File "/usr/local/bin/lifx", line 8, in <module>
Something unexpected happened!! Please file a ticket in the issue tracker! None
=============================================================================== 
Traceback (most recent call last):
  File "/usr/local/bin/lifx", line 8, in <module>
    sys.exit(lifx_main())
  File "/usr/local/lib/python3.9/dist-packages/photons_app/executor.py", line 206, in lifx_main
    return main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/delfick_project/app.py", line 234, in main
    app.mainline(argv, **execute_args)
  File "/usr/local/lib/python3.9/dist-packages/photons_app/executor.py", line 111, in mainline
    super(App, self).mainline(original_argv, print_errors_to, **execute_args)
  File "/usr/local/lib/python3.9/dist-packages/delfick_project/app.py", line 312, in mainline
    self.execute(args_obj, args_dict, extra_args, handler, **execute_args)
  File "/usr/local/lib/python3.9/dist-packages/photons_app/executor.py", line 146, in execute
    task_register.fill_task(
  File "/usr/local/lib/python3.9/dist-packages/photons_app/tasks/tasks.py", line 148, in run_loop
    super().run_loop(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/photons_app/tasks/tasks.py", line 102, in run_loop
    return Runner(self, kwargs).run_loop()
  File "/usr/local/lib/python3.9/dist-packages/photons_app/tasks/runner.py", line 22, in run_loop
    self.Run(self.task.run(**self.kwargs), photons_app, target_register).run()
  File "/usr/local/lib/python3.9/dist-packages/photons_app/tasks/runner.py", line 69, in run
    raise override from None
  File "/usr/local/lib/python3.9/dist-packages/photons_app/tasks/runner.py", line 50, in run
    self.loop.run_until_complete(waiter)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/photons_app/tasks/runner.py", line 87, in wait
    await task
  File "/usr/local/lib/python3.9/dist-packages/photons_app/tasks/tasks.py", line 109, in run
    return await self.execute_task(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/interactor/addon.py", line 40, in execute_task
    await Server(
  File "/usr/local/lib/python3.9/dist-packages/whirlwind/server.py", line 30, in serve
    self.http_server.listen(self.port, self.host)
  File "/usr/local/lib/python3.9/dist-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python3.9/dist-packages/tornado/netutil.py", line 104, in bind_sockets
    socket.getaddrinfo(address, port, family, socket.SOCK_STREAM, 0, flags),
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by Djelibeybi** [comment]
You'll have to edit the file it created to set the correct hostname and IP address. The add-on is trying to start with incorrect (or missing) values. This can happen if it tries to start using the external IP address instead of the container IP address.

**Comment by Djelibeybi** [comment]
FYI, I've removed that other repo. I didn't even realise it was still public.

**Comment by h3mmy** [comment]
I only get time to do this on weekends, so thanks for your patience with helping me. I have confirmed that it is now able to function with hardcoded device discovery and creates the initial config file. I did have to set the ip-address manually as you suggested. Here is the config file that works for reference:
```
interactor:
    host: 10.1.0.25
    port: 6100

    database:
      uri: "{config_root}/interactor.db"

    daemon_options:
        limit: 30 # Limit of 30 messages inflight at any one time
        search_interval: 1800 # do a discovery every 30 minutes
        time_between_queries:
          LIGHT_STATE: 600 # label, power, hsbk every 10 minutes
          VERSION: null # The type of product can be cached forever
          FIRMWARE: 86400 # Cache the firmware version for a day
          GROUP: 780 # Cache group information for 13 minutes
          LOCATION: 9600 # Cache location information for 16 minutes

    zeroconf:
      enabled: true
      ip_address: 10.1.0.25
      name: home-assistant

discovery_options:
  hardcoded_discovery:
    d07xxxxxx25a: "10.0.0.12"
```

Running a curl with discover then returns the device listed in hardcoded_discovery. It works great for the bulbs, but misidentifies the switch as a bulb. Is there an option for me to manually specify this somewhere? I can also open a separate issue if you wish as my original issue is now resolved. And again, thank you for your help.

**Comment by h3mmy** [comment]
Update, I have learned it doesn't matter if it's classified correctly or not. Using RelayMessages (eg. GetRPower) with the correct relay index works. It just took some experimenting to get that right. Thanks for your help. I will close this now.

**Comment by Djelibeybi** [comment]
Glad you got it working!
